# Generated by Django 2.0 on 2018-05-21 19:38

import corp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id_corp', models.AutoField(primary_key=True, serialize=False, verbose_name='ID корпуса')),
                ('name', models.CharField(max_length=100, verbose_name='Название корпуса')),
                ('type', models.CharField(max_length=100, verbose_name='Тип корпуса')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заголовок корпуса',
                'verbose_name_plural': 'Заголовки корпусов',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False, verbose_name='ID текста')),
                ('title', models.CharField(max_length=100, verbose_name='Название текста')),
                ('author', models.CharField(max_length=100, verbose_name='Автор текста')),
                ('theme', models.CharField(max_length=100, verbose_name='Тема текста')),
                ('date', models.DateField(verbose_name='Дата текста')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('file', models.FileField(upload_to=corp.models.texts_path, verbose_name='Текст')),
                ('xml', models.FileField(upload_to='items/xml/', verbose_name='XML')),
                ('id_corp', models.ForeignKey(db_column='id_corp', on_delete=django.db.models.deletion.CASCADE, to='corp.Header', verbose_name='ID корпуса')),
            ],
            options={
                'verbose_name': 'Позиция корпуса',
                'verbose_name_plural': 'Позиции корпусов',
            },
        ),
    ]
