# Generated by Django 2.0 on 2018-06-17 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='xml',
        ),
    ]
